export { LessonBreadcrumbs } from "@/components/lesson/premium/lesson-breadcrumbs";
export { LessonCompletionCard } from "@/components/lesson/lesson-completion-card";
export { LessonCompletionCta } from "@/components/lesson/premium/lesson-completion-cta";
export { KeyTermsGrid } from "@/components/lesson/key-terms-grid";
export { LessonKeyTerms } from "@/components/lesson/premium/lesson-key-terms";
export { LessonMainContent } from "@/components/lesson/premium/lesson-main-content";
export { LessonAIMentorPanel } from "@/components/lesson/premium/lesson-ai-mentor-panel";
export type { LessonAIMentorPanelProps } from "@/components/lesson/premium/lesson-ai-mentor-panel";
/** @deprecated */ export { LessonMentorSidebar } from "@/components/lesson/premium/lesson-mentor-sidebar";
export { MiniCheckpoint } from "@/components/lesson/mini-checkpoint";
export { LessonMiniCheckpoint } from "@/components/lesson/premium/lesson-mini-checkpoint";
export { LessonObjectives } from "@/components/lesson/premium/lesson-objectives";
export { LessonObjective } from "@/components/lesson/premium/lesson-objective";
export { LessonPremiumHeader } from "@/components/lesson/premium/lesson-premium-header";
export { LessonPremiumLayout } from "@/components/lesson/premium/lesson-premium-layout";
export { LessonRightSidebar } from "@/components/lesson/premium/lesson-right-sidebar";
export { LessonPremiumScreen } from "@/components/lesson/premium/lesson-premium-screen";
export { LessonProgressAside } from "@/components/lesson/premium/lesson-progress-aside";
export { LessonContentLegend } from "@/components/lesson/lesson-content-legend";
export { LessonIntroPanel } from "@/components/lesson/lesson-intro-panel";
export { LessonJourneyStrip } from "@/components/lesson/lesson-journey-strip";
export { LessonOutline } from "@/components/lesson/lesson-outline";
export { LessonNavigation } from "@/components/lesson/lesson-navigation";
export { LessonStepNavigation } from "@/components/lesson/premium/lesson-step-navigation";
