-- 9 дополнительных бейджей (кошачьи мемы, всего 17 в каталоге)

ALTER TYPE "AchievementKind" ADD VALUE IF NOT EXISTS 'LESSON_STUDIED';
ALTER TYPE "AchievementKind" ADD VALUE IF NOT EXISTS 'TEST_PASSED';
ALTER TYPE "AchievementKind" ADD VALUE IF NOT EXISTS 'TWO_MODULES_COMPLETE';
ALTER TYPE "AchievementKind" ADD VALUE IF NOT EXISTS 'THREE_MODULES_COMPLETE';
ALTER TYPE "AchievementKind" ADD VALUE IF NOT EXISTS 'PRACTICE_SUBMITTED';
ALTER TYPE "AchievementKind" ADD VALUE IF NOT EXISTS 'MENTOR_CHAT_ACTIVE';
ALTER TYPE "AchievementKind" ADD VALUE IF NOT EXISTS 'TEST_RETRY';
ALTER TYPE "AchievementKind" ADD VALUE IF NOT EXISTS 'ALL_LESSONS_STUDIED';
ALTER TYPE "AchievementKind" ADD VALUE IF NOT EXISTS 'ONE_MODULE_REMAINING';
