INSERT INTO "Answer" ("id", "questionId", "answerText", "isCorrect") VALUES
('cmpouzunb00g9lkse56jrh4wc', 'cmpouzunb00g8lksethqe845q', 'Данные доступны только тем, кому они по работе положены', 't'),
('cmpouzunb00galkse38bglz2l', 'cmpouzunb00g8lksethqe845q', 'Сервис почти никогда не падает', 'f'),
('cmpouzunb00gblkseaelx13xt', 'cmpouzunb00g8lksethqe845q', 'Файлы никто не менял незаметно', 'f'),
('cmpouzunb00gclksesezxeinb', 'cmpouzunb00g8lksethqe845q', 'На сайте есть замочек HTTPS', 'f'),
('cmpouzung00gflksebxzkws12', 'cmpouzung00gelksena6xt9dh', 'Что данные не меняют без разрешения так, чтобы это было незаметно', 't'),
('cmpouzung00gglkse4rye5633', 'cmpouzung00gelksena6xt9dh', 'Что пароль состоит из двенадцати символов', 'f'),
('cmpouzung00ghlkse33e8ely3', 'cmpouzung00gelksena6xt9dh', 'Что сервер стоит в надёжном дата-центре', 'f'),
('cmpouzung00gilksesnn19m0q', 'cmpouzung00gelksena6xt9dh', 'Что у вас установлен антивирус', 'f'),
('cmpouzunj00gllksevrqfsycu', 'cmpouzunj00gklkse99ydeij8', 'Верно', 'f'),
('cmpouzunj00gmlkseh9ojo6kr', 'cmpouzunj00gklkse99ydeij8', 'Неверно', 't'),
('cmpouzunl00gplksezgebm13k', 'cmpouzunl00golkse9pbrzdfa', 'Перейти по ссылке, раз тема учебная', 'f'),
('cmpouzunl00gqlkse799u1h0z', 'cmpouzunl00golkse9pbrzdfa', 'Не кликать: открыть портал через закладку или адрес, который вы проверяли раньше', 't'),
('cmpouzunl00grlksekn9f56sv', 'cmpouzunl00golkse9pbrzdfa', 'Переслать письмо всем одногруппникам для обсуждения', 'f'),
('cmpouzunl00gslkse69icgyjb', 'cmpouzunl00golkse9pbrzdfa', 'Ответить отправителю паролем, чтобы «закрыть вопрос»', 'f'),
('cmpouzunn00gvlksevgw069h2', 'cmpouzunn00gulkse6uhfwep1', 'Вставить и открыть всё, что внутри', 'f'),
('cmpouzunn00gwlksexdh9vck8', 'cmpouzunn00gulkse6uhfwep1', 'Сдать в администрацию/дежурному, не подключая к своему ПК', 't'),
('cmpouzunn00gxlksexjpcyqel', 'cmpouzunn00gulkse6uhfwep1', 'Сначала отключить антивирус, чтобы ничего не удалило файлы', 'f'),
('cmpouzunn00gylksemcgv4mio', 'cmpouzunn00gulkse6uhfwep1', 'Отформатировать флешку и оставить себе', 'f'),
('cmpouzunq00h1lksenb6thimb', 'cmpouzunq00h0lksexe9hsh5u', 'Дать пароль голосом, он же свой', 'f'),
('cmpouzunq00h2lkse1vseuxda', 'cmpouzunq00h0lksexe9hsh5u', 'Отказать и предложить официальный способ: раздать материалы или гостевой доступ, если он есть', 't'),
('cmpouzunq00h3lksev7zrp019', 'cmpouzunq00h0lksexe9hsh5u', 'Войти и не выходить из аккаунта, чтобы ему было удобнее', 'f'),
('cmpouzunq00h4lksevqtnidfb', 'cmpouzunq00h0lksexe9hsh5u', 'Сменить пароль на простой перед входом', 'f'),
('cmpouzuns00h7lksen7g0lvy9', 'cmpouzuns00h6lkseb55rv4y7', 'Зайти сразу: всем же пользуются', 'f'),
('cmpouzuns00h8lksenoxq69aj', 'cmpouzuns00h6lkseb55rv4y7', 'Отложить вход или использовать мобильный интернет / доверенный VPN по правилам колледжа', 't'),
('cmpouzuns00h9lkse4ezcj2py', 'cmpouzuns00h6lkseb55rv4y7', 'Включить инкогнито и считать, что этого достаточно', 'f');