INSERT INTO "Answer" ("id", "questionId", "answerText", "isCorrect") VALUES
('cmpouzuns00halksef8eqe0sc', 'cmpouzuns00h6lkseb55rv4y7', 'Сохранить пароль в браузере для скорости', 'f'),
('cmpouzunv00hdlksei1b3vsht', 'cmpouzunv00hclksejugwaf3j', 'Сразу отправить, вдруг дедлайн', 'f'),
('cmpouzunv00helkse2yricrrh', 'cmpouzunv00hclksejugwaf3j', 'Уточнить через официальный контакт курса и не слать документы в мессенджер без правил', 't'),
('cmpouzunv00hflksej6id5dhu', 'cmpouzunv00hclksejugwaf3j', 'Отправить, но замазать всё кроме фото', 'f'),
('cmpouzunv00hglkse1cpvbmvw', 'cmpouzunv00hclksejugwaf3j', 'Выложить скан в общий чат группы', 'f'),
('cmpouzunx00hjlkseckla3hgl', 'cmpouzunx00hilksexfoj2o0u', 'Ограничить чтение данных посторонним', 'f'),
('cmpouzunx00hklksemtxd9gls', 'cmpouzunx00hilksexfoj2o0u', 'Заметить подмену важной записи', 'f'),
('cmpouzunx00hllksed9i3rod0', 'cmpouzunx00hilksexfoj2o0u', 'Хранить все пароли в одном открытом файле без контроля доступа', 't'),
('cmpouzunx00hmlksevspp625i', 'cmpouzunx00hilksexfoj2o0u', 'Чтобы сервис был доступен, когда он нужен', 'f'),
('cmpouzunz00hplksefzxz97jk', 'cmpouzunz00holksefz0hshx4', 'Верно', 'f'),
('cmpouzunz00hqlksexqhixlj8', 'cmpouzunz00holksefz0hshx4', 'Неверно', 't'),
('cmpouzuof00jalkse8a9adw29', 'cmpouzuof00j9lksexrunkbta', 'Второй способ подтвердить вход помимо пароля', 't'),
('cmpouzuof00jblksezyqstj96', 'cmpouzuof00j9lksexrunkbta', 'Два пароля подряд в одном поле', 'f'),
('cmpouzuof00jclkse3x71i2fa', 'cmpouzuof00j9lksexrunkbta', 'Два монитора на столе', 'f'),
('cmpouzuof00jdlksey14s2v6m', 'cmpouzuof00j9lksexrunkbta', 'Два браузера одновременно', 'f'),
('cmpouzuoh00jglkser41hknpy', 'cmpouzuoh00jflkse3g6wfgdp', 'Потому что при утечке на одном сайте страдают все сервисы с тем же паролем', 't'),
('cmpouzuoh00jhlkseofqht58y', 'cmpouzuoh00jflkse3g6wfgdp', 'Потому что сложный пароль нельзя запомнить', 'f'),
('cmpouzuoh00jilksesy97rzxs', 'cmpouzuoh00jflkse3g6wfgdp', 'Потому что банк запрещает сложные пароли', 'f'),
('cmpouzuoh00jjlkserqd8lsae', 'cmpouzuoh00jflkse3g6wfgdp', 'Потому что 2FA отменяет пароль', 'f'),
('cmpouzuoj00jmlkse85jdqw3o', 'cmpouzuoj00jllkseull73sol', 'Верно', 'f'),
('cmpouzuoj00jnlksenqt6ikdy', 'cmpouzuoj00jllkseull73sol', 'Неверно', 't'),
('cmpouzuok00jqlkseztv0729l', 'cmpouzuok00jplksebh6upmdm', 'Назвать код, если голос уверенный', 'f'),
('cmpouzuok00jrlkseqo6kk9j6', 'cmpouzuok00jplksebh6upmdm', 'Положить трубку и позвонить на номер с карты или с официального сайта', 't'),
('cmpouzuok00jslkse2zpevwdm', 'cmpouzuok00jplksebh6upmdm', 'Сфоткать SMS и кинуть в общий чат', 'f'),
('cmpouzuok00jtlksezmo09i2c', 'cmpouzuok00jplksebh6upmdm', 'Сказать код шёпотом', 'f');