INSERT INTO "Answer" ("id", "questionId", "answerText", "isCorrect") VALUES
('cmpouzuon00jwlkse12ptwjxl', 'cmpouzuon00jvlkse0m9uyunl', 'Отличный пароль, в нём есть знак', 'f'),
('cmpouzuon00jxlkse3s3b10e0', 'cmpouzuon00jvlkse0m9uyunl', 'Слабоват: слишком шаблонно; для важного — уникальная длинная фраза или менеджер', 't'),
('cmpouzuon00jylkse07mj4yhp', 'cmpouzuon00jvlkse0m9uyunl', 'Надёжность не важна, если включён инкогнито', 'f'),
('cmpouzuon00jzlksedj4mgbct', 'cmpouzuon00jvlkse0m9uyunl', 'Надёжность определяется только длиной шести символов', 'f'),
('cmpouzuop00k2lksetg2dil1t', 'cmpouzuop00k1lkse85a6x96m', 'Нет, на форуме и так шутки', 'f'),
('cmpouzuop00k3lkseh6rmx9cy', 'cmpouzuop00k1lkse85a6x96m', 'Да: пусть будет уникальный и длинный, менеджер хранит', 't'),
('cmpouzuop00k4lksey3a8j66k', 'cmpouzuop00k1lkse85a6x96m', 'Только если форум государственный', 'f'),
('cmpouzuop00k5lkse028ac989', 'cmpouzuop00k1lkse85a6x96m', 'Нет, проще один пароль везде', 'f'),
('cmpouzuor00k8lkse334jxn53', 'cmpouzuor00k7lksedrimdoxu', 'Нормально, всё равно свои заходят', 'f'),
('cmpouzuor00k9lkse3wvlnxay', 'cmpouzuor00k7lksedrimdoxu', 'Плохо: это почти публичный второй фактор; убрать в сейф/домой', 't'),
('cmpouzuor00kalksek1hg2tzg', 'cmpouzuor00k7lksedrimdoxu', 'Отлично, так их не потеряешь', 'f'),
('cmpouzuor00kblkset9e9gmxh', 'cmpouzuor00k7lksedrimdoxu', 'Нормально, если написать мелким шрифтом', 'f'),
('cmpouzuot00kelkse5b8h9g4w', 'cmpouzuot00kdlksexd13f9in', 'Дать, раз друг', 'f'),
('cmpouzuot00kflksege1oljjo', 'cmpouzuot00kdlksexd13f9in', 'Отказать: общий доступ ломает аудит и включает вас в риски', 't'),
('cmpouzuot00kglksebbhxn0rm', 'cmpouzuot00kdlksexd13f9in', 'Дать, но сменить пароль через месяц', 'f'),
('cmpouzuot00khlkse331s1om2', 'cmpouzuot00kdlksexd13f9in', 'Дать только если он пообещает не трогать скины', 'f'),
('cmpouzuov00kklksee90l19t5', 'cmpouzuov00kjlksew0vqk1rz', 'Код из SMS нельзя диктовать незнакомцу по телефону', 't'),
('cmpouzuov00kllksesk3gtu1v', 'cmpouzuov00kjlksew0vqk1rz', 'SMS-2FA всегда строго сильнее аппаратного ключа в любой ситуации', 'f'),
('cmpouzuov00kmlkse5e2ko4h9', 'cmpouzuov00kjlksew0vqk1rz', 'Приложение-аутентификатор часто предпочтительнее SMS, если есть выбор', 't'),
('cmpouzuov00knlkseu620022r', 'cmpouzuov00kjlksew0vqk1rz', 'Код из SMS можно выложить в сторис, если красивое число', 'f'),
('cmpouzuoy00kqlksem2oc7isl', 'cmpouzuoy00kplkse4yqj4xim', 'Мастер-пароль — от менеджера паролей, не от соцсети', 't'),
('cmpouzuoy00krlksef2n4sivz', 'cmpouzuoy00kplkse4yqj4xim', 'Резервные коды 2FA — одноразовый запас при потере второго фактора', 't'),
('cmpouzuoy00kslkseg9o1s93l', 'cmpouzuoy00kplkse4yqj4xim', 'Мастер-пароль — это пароль от Wi‑Fi в общаге', 'f'),
('cmpouzuoy00ktlksehyb4vjxy', 'cmpouzuoy00kplkse4yqj4xim', 'Резервные коды можно светить в общем чате «на всякий случай»', 'f'),
('cmpouzupd00mblksek03abfmr', 'cmpouzupd00malksemu3ya2jl', 'Попытка выманить данные или действие через обман', 't');