INSERT INTO "Answer" ("id", "questionId", "answerText", "isCorrect") VALUES
('cmpouzupd00mclksew7wyzpu8', 'cmpouzupd00malksemu3ya2jl', 'Только рассылка с вредоносным вложением', 'f'),
('cmpouzupd00mdlksenjzwl71s', 'cmpouzupd00malksemu3ya2jl', 'Только взлом пароля перебором', 'f'),
('cmpouzupd00melksezd588qfj', 'cmpouzupd00malksemu3ya2jl', 'Только атака на Wi‑Fi', 'f'),
('cmpouzupf00mhlkseiaj7r2cn', 'cmpouzupf00mglkse0nhjr08o', 'Манипуляции с человеком, чтобы получить доступ или информацию', 't'),
('cmpouzupf00milksewldg6wx8', 'cmpouzupf00mglkse0nhjr08o', 'Настройка файрвола', 'f'),
('cmpouzupf00mjlkseunnq09ms', 'cmpouzupf00mglkse0nhjr08o', 'Только автоматический подбор пароля', 'f'),
('cmpouzupf00mklksew13j9eat', 'cmpouzupf00mglkse0nhjr08o', 'Только шифрование диска', 'f'),
('cmpouzuph00mnlksemuevfb1w', 'cmpouzuph00mmlkseuj8hz7it', 'Верно', 'f'),
('cmpouzuph00molksewew0365u', 'cmpouzuph00mmlkseuj8hz7it', 'Неверно', 't'),
('cmpouzupk00mrlksen71ln2fx', 'cmpouzupk00mqlkse9fhcg1mo', 'Скинуть, турнир важный', 'f'),
('cmpouzupk00mslksefoh4tkwn', 'cmpouzupk00mqlkse9fhcg1mo', 'Проверить через официальный канал турнира; не делиться кодами доступа', 't'),
('cmpouzupk00mtlkseaz4efm0d', 'cmpouzupk00mqlkse9fhcg1mo', 'Спросить у другого «админа» в личке', 'f'),
('cmpouzupk00mulkse3gc4ll55', 'cmpouzupk00mqlkse9fhcg1mo', 'Скинуть, если аватарка красивая', 'f'),
('cmpouzupn00mxlkse2rjipbvj', 'cmpouzupn00mwlkseigl6x0yq', 'Запустить, чтобы увидеть сумму', 'f'),
('cmpouzupn00mylkse2mmolb0e', 'cmpouzupn00mwlkseigl6x0yq', 'Не запускать; зайти в сервис через проверенный адрес и проверить счета', 't'),
('cmpouzupn00mzlkseio76g5tt', 'cmpouzupn00mwlkseigl6x0yq', 'Переслать преподавателю для анализа с запуском', 'f'),
('cmpouzupn00n0lksecbd78695', 'cmpouzupn00mwlkseigl6x0yq', 'Сохранить на флешку и дать другу', 'f'),
('cmpouzupp00n3lkseu8x1hrwb', 'cmpouzupp00n2lkser9x0wyqb', 'Нормальную логистику', 'f'),
('cmpouzupp00n4lksei11cd0my', 'cmpouzupp00n2lkser9x0wyqb', 'Выманивание одноразового кода / мошенничество', 't'),
('cmpouzupp00n5lkseqp8n288t', 'cmpouzupp00n2lkser9x0wyqb', 'Проверку качества связи', 'f'),
('cmpouzupp00n6lkset4qtxmyt', 'cmpouzupp00n2lkser9x0wyqb', 'Работу 2FA магазина', 'f'),
('cmpouzupr00n9lksevk8dfeg6', 'cmpouzupr00n8lksep0iovdxz', 'Войти и не выходить из сессии', 'f'),
('cmpouzupr00nalkse27ycxsfp', 'cmpouzupr00n8lksep0iovdxz', 'Не вводить свои креды; использовать своё устройство или официальный гостевой доступ', 't'),
('cmpouzupr00nblkse7sys4ni2', 'cmpouzupr00n8lksep0iovdxz', 'Войти, если он отвернётся', 'f'),
('cmpouzupr00nclkse5pablriz', 'cmpouzupr00n8lksep0iovdxz', 'Дать пароль устно', 'f');