INSERT INTO "Answer" ("id", "questionId", "answerText", "isCorrect") VALUES
('cmpouzupu00nflkse6kzync87', 'cmpouzupu00nelkse2o1fwrmz', 'Кликнуть, если в превью видно слово bank', 'f'),
('cmpouzupu00nglksedej3gt4z', 'cmpouzupu00nelkse2o1fwrmz', 'Не кликать; открыть банк через официальное приложение или проверенный URL', 't'),
('cmpouzupu00nhlkselm3wgv29', 'cmpouzupu00nelkse2o1fwrmz', 'Кликнуть из любопытства в инкогнито', 'f'),
('cmpouzupu00nilkseb7mkg2db', 'cmpouzupu00nelkse2o1fwrmz', 'Спросить совета в публичном чате', 'f'),
('cmpouzupx00nllkseuf4axmm2', 'cmpouzupx00nklksez40dolbz', 'Верно', 'f'),
('cmpouzupx00nmlksexeh77jn7', 'cmpouzupx00nklksez40dolbz', 'Неверно', 't'),
('cmpouzupz00nplkseepktyqus', 'cmpouzupz00nolksetuqoegt9', 'Сообщить в учебный ИТ/преподавателю по каналу, если письмо маскируется под колледж', 't'),
('cmpouzupz00nqlkse8sz3xo7d', 'cmpouzupz00nolksetuqoegt9', 'Сразу кидать скриншот с персональными данными в публичный чат', 'f'),
('cmpouzupz00nrlkseok40f38w', 'cmpouzupz00nolksetuqoegt9', 'Игнорировать навсегда без проверки, если есть дедлайн в письме', 'f'),
('cmpouzupz00nslkseyjm65hxa', 'cmpouzupz00nolksetuqoegt9', 'Покупать «антихак» по ссылке из того же письма', 'f'),
('cmpouzuqc00palkse44kkzqx2', 'cmpouzuqc00p9lksepk0r53mc', 'Закрывать известные уязвимости и улучшать стабильность', 't'),
('cmpouzuqc00pblksesffvfolb', 'cmpouzuqc00p9lksepk0r53mc', 'Удалять ваши личные файлы', 'f'),
('cmpouzuqc00pclksejy9zm9my', 'cmpouzuqc00p9lksepk0r53mc', 'Ускорять интернет всегда', 'f'),
('cmpouzuqc00pdlkselheduuxn', 'cmpouzuqc00p9lksepk0r53mc', 'Менять пароль администратора без спроса', 'f'),
('cmpouzuqe00pglksesvx9mrb6', 'cmpouzuqe00pflkseuw2f58ca', 'Блокировка экрана, шифрование данных телефона (если доступно), не хранить пароли в открытом виде', 't'),
('cmpouzuqe00phlksexa8638p9', 'cmpouzuqe00pflkseuw2f58ca', 'Только яркая обложка чехла', 'f'),
('cmpouzuqe00pilksespgx6mlm', 'cmpouzuqe00pflkseuw2f58ca', 'Только отключение Bluetooth', 'f'),
('cmpouzuqe00pjlkseveeols2g', 'cmpouzuqe00pflkseuw2f58ca', 'Только смена обоев', 'f'),
('cmpouzuqh00pmlksehkw1yvjo', 'cmpouzuqh00pllkse7cmq789k', 'Верно', 'f'),
('cmpouzuqh00pnlksezj5in2dj', 'cmpouzuqh00pllkse7cmq789k', 'Неверно', 't'),
('cmpouzuqj00pqlkset9c9gc3r', 'cmpouzuqj00pplkse7hgv4y51', 'Норм, если отключить антивирус', 'f'),
('cmpouzuqj00prlkset0hc9rk8', 'cmpouzuqj00pplkse7hgv4y51', 'Лучше легальные бесплатные аналоги; неизвестный кряк — высокий риск', 't'),
('cmpouzuqj00pslksetvanr6nq', 'cmpouzuqj00pplkse7hgv4y51', 'Безопасно, если друг уже поставил', 'f'),
('cmpouzuqj00ptlksesdc1jf2w', 'cmpouzuqj00pplkse7hgv4y51', 'Безопасно, если скачать ночью', 'f'),
('cmpouzuql00pwlkserit0bp91', 'cmpouzuql00pvlkse7ivliixy', 'Пароль/PIN на входе и авто-блокировка через короткий таймаут', 't');