INSERT INTO "Answer" ("id", "questionId", "answerText", "isCorrect") VALUES
('cmpouzuql00pxlksehw04b2ji', 'cmpouzuql00pvlkse7ivliixy', 'Полностью отключить брандмауэр для скорости', 'f'),
('cmpouzuql00pylkse4jtgg63a', 'cmpouzuql00pvlkse7ivliixy', 'Стикер с паролем на крышке', 'f'),
('cmpouzuql00pzlksevv2r34br', 'cmpouzuql00pvlkse7ivliixy', 'Общий доступ к папке без пароля «друзьям»', 'f'),
('cmpouzuqn00q2lkse0t9grs3d', 'cmpouzuqn00q1lksemm7fjnpc', 'Да, мышь простая', 'f'),
('cmpouzuqn00q3lksepr94gcfe', 'cmpouzuqn00q1lksemm7fjnpc', 'Лучше проверенные устройства: непонятные гаджеты — лишний риск', 't'),
('cmpouzuqn00q4lkse97639sef', 'cmpouzuqn00q1lksemm7fjnpc', 'Да, если выключить Wi‑Fi', 'f'),
('cmpouzuqn00q5lkseoti788on', 'cmpouzuqn00q1lksemm7fjnpc', 'Да, если только для игр', 'f'),
('cmpouzuqp00q8lkses91d6m52', 'cmpouzuqp00q7lksetzn29tma', 'Идеально для любых сбоев', 'f'),
('cmpouzuqp00q9lksey38rwbmv', 'cmpouzuqp00q7lksetzn29tma', 'Лучше чем ничего; чаще и по важным файлам надёжнее', 't'),
('cmpouzuqp00qalkseg9a96vcw', 'cmpouzuqp00q7lksetzn29tma', 'Не нужно, если есть облако без проверки', 'f'),
('cmpouzuqp00qblksem99po6yj', 'cmpouzuqp00q7lksetzn29tma', 'Достаточно фото экрана в галерее', 'f'),
('cmpouzuqs00qelksengchyk2r', 'cmpouzuqs00qdlkse5ugtn75k', 'Включить, удобно же', 'f'),
('cmpouzuqs00qflksekpwip91q', 'cmpouzuqs00qdlkse5ugtn75k', 'Не открывать общий доступ без пароля и минимальных прав', 't'),
('cmpouzuqs00qglkse747avxep', 'cmpouzuqs00qdlkse5ugtn75k', 'Только для фильмов в 4K', 'f'),
('cmpouzuqs00qhlksegt40nrzx', 'cmpouzuqs00qdlkse5ugtn75k', 'Да, если отключить антивирус', 'f'),
('cmpouzuqt00qklkseui0sahnp', 'cmpouzuqt00qjlksemf1m8e7t', 'Шифрование диска снижает ценность украденного ноутбука для вора-любителя', 't'),
('cmpouzuqt00qllkse8g7z1ldv', 'cmpouzuqt00qjlksemf1m8e7t', 'Шифрование отменяет необходимость в пароле на входе', 'f'),
('cmpouzuqt00qmlkseosox10ft', 'cmpouzuqt00qjlksemf1m8e7t', 'Бэкап всё равно нужен от сбоев и случайного удаления', 't'),
('cmpouzuqt00qnlksehnbv1jn6', 'cmpouzuqt00qjlksemf1m8e7t', 'Шифрование делает Wi‑Fi автоматически безопасным', 'f'),
('cmpouzuqw00qqlksevlmjgwqa', 'cmpouzuqw00qplkseghs6trhe', 'Верно', 'f'),
('cmpouzuqw00qrlkse8mtwsf65', 'cmpouzuqw00qplkseghs6trhe', 'Неверно', 't'),
('cmpouzur800sblkseui5zfltr', 'cmpouzur800salksedrpe6s09', 'Трафик между браузером и сайтом по пути шифруется', 't'),
('cmpouzur800sclksef1ta6osv', 'cmpouzur800salksedrpe6s09', 'Владелец сайта проверен государством лично', 'f'),
('cmpouzur800sdlksewtf5m6nu', 'cmpouzur800salksedrpe6s09', 'Рекламы не будет', 'f'),
('cmpouzur800selkse17lfhqhl', 'cmpouzur800salksedrpe6s09', 'Пароль можно вводить даже на подозрительной копии банка', 'f');