INSERT INTO "Answer" ("id", "questionId", "answerText", "isCorrect") VALUES
('cmpouzura00shlkserj0cick7', 'cmpouzura00sglkse8vl1aoj3', 'Данные, которые сайт оставляет в браузере (сессии, настройки, иногда трекинг)', 't'),
('cmpouzura00silkserumexbkq', 'cmpouzura00sglkse8vl1aoj3', 'Вирус', 'f'),
('cmpouzura00sjlkseedty3jns', 'cmpouzura00sglkse8vl1aoj3', 'Только сертификат HTTPS', 'f'),
('cmpouzura00sklkseffnup97f', 'cmpouzura00sglkse8vl1aoj3', 'Только пароль Wi‑Fi', 'f'),
('cmpouzurc00snlksezrmmif8c', 'cmpouzurc00smlksei2ilb59p', 'Верно', 'f'),
('cmpouzurc00solksev34mrwih', 'cmpouzurc00smlksei2ilb59p', 'Неверно', 't'),
('cmpouzurd00srlkse80hu2iva', 'cmpouzurd00sqlkse9bzs9emh', 'Разрешить всегда, так вежливее', 'f'),
('cmpouzurd00sslkseme4g12ku', 'cmpouzurd00sqlkse9bzs9emh', 'Скорее отказать, пока не понятно, что за сайт и зачем уведомления', 't'),
('cmpouzurd00stlksenu0azfsj', 'cmpouzurd00sqlkse9bzs9emh', 'Разрешить только ночью', 'f'),
('cmpouzurd00sulkse63y8wytt', 'cmpouzurd00sqlkse9bzs9emh', 'Разрешить, если есть HTTPS', 'f'),
('cmpouzurg00sxlkse84y71ju3', 'cmpouzurg00swlksezi4zitys', 'Да, скидки важнее', 'f'),
('cmpouzurg00sylksetmzbfkec', 'cmpouzurg00swlksezi4zitys', 'Подозрительно: не ставить без крайней нужды и проверенного издателя', 't'),
('cmpouzurg00szlksealawxuyp', 'cmpouzurg00swlksezi4zitys', 'Да, если 5 звёзд', 'f'),
('cmpouzurg00t0lksepkg3fh6c', 'cmpouzurg00swlksezi4zitys', 'Да, если друг поставил', 'f'),
('cmpouzuri00t3lkse0r6ajmhd', 'cmpouzuri00t2lkse9667ivzb', 'Кликнуть, bit.ly безопасен всегда', 'f'),
('cmpouzuri00t4lkseqk2ol0w8', 'cmpouzuri00t2lkse9667ivzb', 'Не кликать; открыть почту через приложение или набранный вручную адрес', 't'),
('cmpouzuri00t5lkseqeodal0g', 'cmpouzuri00t2lkse9667ivzb', 'Кликнуть в Tor и не думать', 'f'),
('cmpouzuri00t6lksej67dahwx', 'cmpouzuri00t2lkse9667ivzb', 'Спросить в чате, кликать ли', 'f'),
('cmpouzurj00t9lkse85ui6oqm', 'cmpouzurj00t8lksebbzjzgd8', 'Скачать для старых курсов', 'f'),
('cmpouzurj00talksemrnehc3i', 'cmpouzurj00t8lksebbzjzgd8', 'Игнорировать: Flash мёртв, сообщение подозрительное', 't'),
('cmpouzurj00tblksejhklh4wj', 'cmpouzurj00t8lksebbzjzgd8', 'Спросить у генеративного ИИ, настоящий ли сайт, и сделать как скажет', 'f'),
('cmpouzurj00tclksevdwgf307', 'cmpouzurj00t8lksebbzjzgd8', 'Установить на виртуалку без сети', 'f'),
('cmpouzurl00tflkseasj1r0by', 'cmpouzurl00telksegu3k7k0a', 'Оплатить быстро, пока кофе горячий', 'f'),
('cmpouzurl00tglkse709dbt3u', 'cmpouzurl00telksegu3k7k0a', 'Использовать мобильный интернет или отложить до доверенной сети', 't'),
('cmpouzurl00thlksen1uq0n7m', 'cmpouzurl00telksegu3k7k0a', 'Отключить HTTPS для скорости', 'f');