INSERT INTO "Answer" ("id", "questionId", "answerText", "isCorrect") VALUES
('cmpouzurl00tilksepg72i851', 'cmpouzurl00telksegu3k7k0a', 'Сохранить карту в заметках для скорости', 'f'),
('cmpouzurn00tllkse9zlwxytd', 'cmpouzurn00tklksed5oxow7v', 'Замочек гарантирует, что перед вами не фишинговая копия банка', 't'),
('cmpouzurn00tmlkseae8pevai', 'cmpouzurn00tklksed5oxow7v', 'Замочек связан с шифрованием соединения', 'f'),
('cmpouzurn00tnlkse166ffkq8', 'cmpouzurn00tklksed5oxow7v', 'Подделать иконку в описании могут в материалах обучения', 'f'),
('cmpouzurn00tolkseurgyfhwr', 'cmpouzurn00tklksed5oxow7v', 'Адрес домена всё равно нужно читать внимательно', 'f'),
('cmpouzurq00trlkse6c644p21', 'cmpouzurq00tqlksehwglwj3j', 'DNS — переводит имя сайта в адрес сервера', 't'),
('cmpouzurq00tslkse2jr8sdj3', 'cmpouzurq00tqlksehwglwj3j', 'VPN — гарантия, что сайт честный', 'f'),
('cmpouzurq00ttlkse9os90sz1', 'cmpouzurq00tqlksehwglwj3j', 'VPN — защищённый туннель до узла VPN-провайдера', 't'),
('cmpouzurq00tulksevpx4oema', 'cmpouzurq00tqlksehwglwj3j', 'DNS — хранит пароли сайтов', 'f'),
('cmpouzus200vclkse2va769ec', 'cmpouzus200vblkse6l49y8ac', 'Идентификатор устройства/узла в сети', 't'),
('cmpouzus200vdlkselz1c6lvh', 'cmpouzus200vblkse6l49y8ac', 'Пароль от Wi‑Fi', 'f'),
('cmpouzus200velksexn3t8691', 'cmpouzus200vblkse6l49y8ac', 'Имя файла в Linux', 'f'),
('cmpouzus200vflksex81ov0tf', 'cmpouzus200vblkse6l49y8ac', 'Тип шифрования почты', 'f'),
('cmpouzus500vilksehp4ecq9w', 'cmpouzus500vhlkseudeztiir', 'Служба, которая сопоставляет имя хоста и IP-адрес', 't'),
('cmpouzus500vjlksey4nm8glz', 'cmpouzus500vhlkseudeztiir', 'Антивирус сети', 'f'),
('cmpouzus500vklkse1m6f7gy8', 'cmpouzus500vhlkseudeztiir', 'Протокол отправки файлов', 'f'),
('cmpouzus500vllksezm2q7d8w', 'cmpouzus500vhlkseudeztiir', 'Только брандмауэр', 'f'),
('cmpouzus700volksezepyk7nf', 'cmpouzus700vnlksen1gj168p', 'Верно', 't'),
('cmpouzus700vplksew7dcwuvh', 'cmpouzus700vnlksen1gj168p', 'Неверно', 'f'),
('cmpouzus800vslkse93giiifc', 'cmpouzus800vrlksey6vfl322', 'Вставить и запустить, если много плюсов в чате', 'f'),
('cmpouzus800vtlkse181ptnlu', 'cmpouzus800vrlksey6vfl322', 'Не запускать; спросить преподавателя или использовать лабораторный сценарий', 't'),
('cmpouzus800vulksezxkxfmp5', 'cmpouzus800vrlksey6vfl322', 'Запустить без sudo', 'f'),
('cmpouzus800vvlksefv7irdr3', 'cmpouzus800vrlksey6vfl322', 'Сначала отключить сеть', 'f'),
('cmpouzusa00vylksetmyc2hh3', 'cmpouzusa00vxlkseyl9mgtsv', 'Гарантированно вас взломали', 'f'),
('cmpouzusa00vzlkse82c496nu', 'cmpouzusa00vxlkseyl9mgtsv', 'Проблемы канала/маршрута; сервис может лагать', 't');