INSERT INTO "Answer" ("id", "questionId", "answerText", "isCorrect") VALUES
('cmpouzusa00w0lksei1jkx338', 'cmpouzusa00vxlkseyl9mgtsv', 'Нужно сменить пароль на qwerty', 'f'),
('cmpouzusa00w1lksefubliop5', 'cmpouzusa00vxlkseyl9mgtsv', 'Нужно удалить браузер', 'f'),
('cmpouzusc00w4lksebjt0c3ou', 'cmpouzusc00w3lksehu9s1x9t', 'Любой пользователь системы', 'f'),
('cmpouzusc00w5lksegp7iesw8', 'cmpouzusc00w3lksehu9s1x9t', 'Только владелец файла', 't'),
('cmpouzusc00w6lksexhqbwtyo', 'cmpouzusc00w3lksehu9s1x9t', 'Только root всегда', 'f'),
('cmpouzusc00w7lkse4xmijjj2', 'cmpouzusc00w3lksehu9s1x9t', 'Все гости сети', 'f'),
('cmpouzuse00walksexja1c645', 'cmpouzuse00w9lkseekotflk1', 'Безопасно, если скрипт короткий', 'f'),
('cmpouzuse00wblksefh44m7l5', 'cmpouzuse00w9lkseekotflk1', 'Опасно: не исполнять неизвестные скрипты из чатов', 't'),
('cmpouzuse00wclksensikdrf4', 'cmpouzuse00w9lkseekotflk1', 'Безопасно, если отключить Wi‑Fi', 'f'),
('cmpouzuse00wdlksezu492d35', 'cmpouzuse00w9lkseekotflk1', 'Норм для продакшена без бэкапа', 'f'),
('cmpouzusg00wglkse2muin9ab', 'cmpouzusg00wflksewxs8tjws', 'Сделать, чтобы «заработало»', 'f'),
('cmpouzusg00whlkseem56pfjt', 'cmpouzusg00wflksewxs8tjws', 'Отказаться: искать причину проблемы без открытия всех прав', 't'),
('cmpouzusg00wilksedybhcg09', 'cmpouzusg00wflksewxs8tjws', 'Сделать только на папке загрузок', 'f'),
('cmpouzusg00wjlksedakohp6a', 'cmpouzusg00wflksewxs8tjws', 'Сделать, если препод не видит', 'f'),
('cmpouzush00wmlksezro40nrg', 'cmpouzush00wllksekaso16wy', 'Верно', 'f'),
('cmpouzush00wnlkse8h3mp1oo', 'cmpouzush00wllksekaso16wy', 'Неверно', 't'),
('cmpouzusj00wqlkse7d6mhhc2', 'cmpouzusj00wplkse0uj0sd3p', 'Логи помогают понять последовательность событий после ошибки', 't'),
('cmpouzusj00wrlkse7jksffrp', 'cmpouzusj00wplkse0uj0sd3p', 'Логи заменяют антивирус полностью', 'f'),
('cmpouzusj00wslksesho4p222', 'cmpouzusj00wplkse0uj0sd3p', 'Удаление логов при разборе инцидента — плохая практика', 't'),
('cmpouzusj00wtlksewb2kvm95', 'cmpouzusj00wplkse0uj0sd3p', 'Логи всегда содержат пароли в открытом виде', 'f'),
('cmpouzusv00ydlksezma6i01l', 'cmpouzusv00yclksefffvyexb', 'Чтобы при утечке базы нельзя было просто прочитать пароли', 't'),
('cmpouzusv00yelksemx4x2vtd', 'cmpouzusv00yclksefffvyexb', 'Чтобы админ мог видеть пароли студентов', 'f'),
('cmpouzusv00yflkse7jgfmb0j', 'cmpouzusv00yclksefffvyexb', 'Чтобы пароль стал короче', 'f'),
('cmpouzusv00yglksef55hlss7', 'cmpouzusv00yclksefffvyexb', 'Чтобы не использовать соль', 'f'),
('cmpouzusw00yjlksetcgozxip', 'cmpouzusw00yilkse5scly0nq', 'Способ представить данные текстом; это не «шифрование от друзей»', 't');