INSERT INTO "Answer" ("id", "questionId", "answerText", "isCorrect") VALUES
('cmpouzusw00yklkse6qkb2z6t', 'cmpouzusw00yilkse5scly0nq', 'Надёжное военное шифрование', 'f'),
('cmpouzusw00yllksebhs7pj15', 'cmpouzusw00yilkse5scly0nq', 'Удаление вирусов', 'f'),
('cmpouzusw00ymlksexqrgr7x8', 'cmpouzusw00yilkse5scly0nq', 'То же самое, что HTTPS', 'f'),
('cmpouzusy00yplkse2ajzgzwt', 'cmpouzusy00yolkseb678xmwr', 'Верно', 't'),
('cmpouzusy00yqlksefqf9n3jp', 'cmpouzusy00yolkseb678xmwr', 'Неверно', 'f'),
('cmpouzut000ytlksezaur1vx9', 'cmpouzut000yslkse61sgedzo', 'Игнорировать, размер совпал', 'f'),
('cmpouzut000yulkseze0z909e', 'cmpouzut000yslkse61sgedzo', 'Считать файл подозрительным: перекачать с официального источника', 't'),
('cmpouzut000yvlksew9ag54h5', 'cmpouzut000yslkse61sgedzo', 'Удалить антивирус и попробовать снова', 'f'),
('cmpouzut000ywlkseeczmwejz', 'cmpouzut000yslkse61sgedzo', 'Запустить «от имени администратора»', 'f'),
('cmpouzut200yzlksee37vbrgd', 'cmpouzut200yylkseaqjo5u5g', 'Отличная идея', 'f'),
('cmpouzut200z0lksewj08iuzf', 'cmpouzut200yylkseaqjo5u5g', 'Плохо: Base64 не защищает секрет; нужны нормальные практики хранения', 't'),
('cmpouzut200z1lksejewy2bai', 'cmpouzut200yylkseaqjo5u5g', 'Норм, если не публиковать базу', 'f'),
('cmpouzut200z2lkseljlezaa6', 'cmpouzut200yylkseaqjo5u5g', 'Норм для MVP', 'f'),
('cmpouzut400z5lksescrcvc0n', 'cmpouzut400z4lksexn13zjum', 'Гарантирует, что вы не на поддельной странице с похожим дизайном', 't'),
('cmpouzut400z6lksewuka42co', 'cmpouzut400z4lksexn13zjum', 'Шифрует трафик между браузером и сервером', 'f'),
('cmpouzut400z7lksecwe8ycqr', 'cmpouzut400z4lksexn13zjum', 'Снижает шанс простого подслушивания на пути', 'f'),
('cmpouzut400z8lkseoradx2xf', 'cmpouzut400z4lksexn13zjum', 'Работает как транспортный слой', 'f'),
('cmpouzut600zblksenmiuzssv', 'cmpouzut600zalkse6ingdzpc', 'Отличный стартап', 'f'),
('cmpouzut600zclksevolfa72z', 'cmpouzut600zalkse6ingdzpc', 'Плохая идея: использовать проверенные решения, а не самодельный шифр', 't'),
('cmpouzut600zdlkse3f3py05l', 'cmpouzut600zalkse6ingdzpc', 'Норм, если ключ 8 символов', 'f'),
('cmpouzut600zelksed7xgmbms', 'cmpouzut600zalkse6ingdzpc', 'Норм, если не публиковать', 'f'),
('cmpouzut800zhlkseredv3kht', 'cmpouzut800zglkseml946mlw', 'Интернет стал быстрее', 'f'),
('cmpouzut800zilksei63bwvru', 'cmpouzut800zglkseml946mlw', 'Пакет от ожидаемого издателя и не подменён по дороге (в рамках цепочки доверия)', 't'),
('cmpouzut800zjlkse25r27yv3', 'cmpouzut800zglkseml946mlw', 'Пароль не нужен', 'f'),
('cmpouzut800zklkse6mqayrmy', 'cmpouzut800zglkseml946mlw', 'Фишинг невозможен', 'f');