INSERT INTO "Answer" ("id", "questionId", "answerText", "isCorrect") VALUES
('cmpouzuta00znlkse1myt3iep', 'cmpouzuta00zmlkseywufp6ip', '«Мы придумали свой шифр за вечер — это безопасно для пользователей»', 't'),
('cmpouzuta00zolkse7bwjs8hk', 'cmpouzuta00zmlkseywufp6ip', '«Пароль на сервере часто хранят в виде хеша»', 'f'),
('cmpouzuta00zplkse6jgr4sp6', 'cmpouzuta00zmlkseywufp6ip', '«Публичный ключ можно распространять в рамках асимметрии»', 'f'),
('cmpouzuta00zqlksee0xiloop', 'cmpouzuta00zmlkseywufp6ip', '«Соль помогает против таблиц для угадывания паролей»', 'f'),
('cmpouzutc00ztlksev61ls44f', 'cmpouzutc00zslkse9k7wlrdn', 'Хеш пароля — удобно проверить ввод, не храня пароль открыто', 't'),
('cmpouzutc00zulksef5k9gvta', 'cmpouzutc00zslkse9k7wlrdn', 'Подпись файла — про «кто выпустил» и «не менялось ли»', 't'),
('cmpouzutc00zvlkse70vbclrm', 'cmpouzutc00zslkse9k7wlrdn', 'Base64 — надёжное хранение паролей', 'f'),
('cmpouzutc00zwlksekifp5rne', 'cmpouzutc00zslkse9k7wlrdn', 'HTTPS — замена проверки домена в браузере', 'f'),
('cmpouzuto011elksewt0skk83', 'cmpouzuto011dlksew8mvorax', 'Событие, которое нарушает политику безопасности или создаёт риск вреда', 't'),
('cmpouzuto011flkseit1rpl2j', 'cmpouzuto011dlksew8mvorax', 'Любой перезапуск сервера', 'f'),
('cmpouzuto011glkse86nole5e', 'cmpouzuto011dlksew8mvorax', 'Успешный деплой', 'f'),
('cmpouzuto011hlkseiobcys2c', 'cmpouzuto011dlksew8mvorax', 'Плановый бэкап', 'f'),
('cmpouzutq011klksekau83c4m', 'cmpouzutq011jlkselv3s5rnb', 'Сопоставить разные записи, чтобы понять цепочку «что происходило»', 't'),
('cmpouzutq011llksey6x6puth', 'cmpouzutq011jlkselv3s5rnb', 'Удалить логи', 'f'),
('cmpouzutq011mlksepmdxan0c', 'cmpouzutq011jlkselv3s5rnb', 'Установить игру на сервер', 'f'),
('cmpouzutq011nlksegrgy7o99', 'cmpouzutq011jlkselv3s5rnb', 'Только сменить пароль root', 'f'),
('cmpouzuts011qlkseuh7wle6u', 'cmpouzuts011plkse4na0l54p', 'Верно', 'f'),
('cmpouzuts011rlksevrq2acfl', 'cmpouzuts011plkse4na0l54p', 'Неверно', 't'),
('cmpouzutu011ulkse7zlaz3q4', 'cmpouzutu011tlkseghguxkf8', 'Выложить логи в Telegram «кто виноват»', 'f'),
('cmpouzutu011vlkseb5qgfe76', 'cmpouzutu011tlkseghguxkf8', 'Сообщить ответственному по регламенту, проверить устройство/гео, не удалять следы', 't'),
('cmpouzutu011wlksesf9vszsg', 'cmpouzutu011tlkseghguxkf8', 'Сразу форматировать сервер', 'f'),
('cmpouzutu011xlksebb804tqp', 'cmpouzutu011tlkseghguxkf8', 'Игнорировать как VPN', 'f'),
('cmpouzutv0120lksetk0bvu3d', 'cmpouzutv011zlksewlsw60ai', 'Нормальное чтение лекций', 'f'),
('cmpouzutv0121lksevasp0it6', 'cmpouzutv011zlksewlsw60ai', 'Подозрительное сканирование или ботнет-активность', 't'),
('cmpouzutv0122lkse651d4ymv', 'cmpouzutv011zlksewlsw60ai', 'Резервное копирование', 'f');